[package]
name = "vgpu-bench"
description = "A testing framework for vector graphic rendering libraries"
version = "0.1.0"
authors = ["Spencer Imbleau <spencer@imbleau.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/simbleau/vgpu-bench"
keywords = ["gpu", "vector", "graphics"]
exclude = [
    "assets/",
    "examples/",
    "tests/",
]


[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/bin.rs"

[workspace]
members = [
    "crates/renderer",
    "crates/svg-generator",
    "crates/tess-lib",
    "crates/render-lib",
    "crates/naive-renderer",
]

[dependencies]
renderer = { package = "renderer", path = "crates/renderer" }
tess = { package = "tess-lib", path = "crates/tess-lib" }
rendering = { package = "render-lib", path = "crates/render-lib" }
naive-renderer = { package = "naive-renderer", path = "crates/naive-renderer" }
svg-gen = { package = "svg-generator", path = "crates/svg-generator" }

const_format = "0.2.21"
lyon = { version ="0.17.5", features = ["extra"] }
usvg = "0.19.0"
walkdir = "2"
csv = "1.1"

[dev-dependencies]
