[package]
name = "vgpu-bench"
description = "A testing framework for vector graphic rendering libraries"
version = "0.1.0"
authors = ["Spencer Imbleau <spencer@imbleau.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/simbleau/vgpu-bench"
keywords = ["gpu", "vector", "graphics"]
exclude = [
    "assets/",
    "examples/",
    "tests/",
]

[workspace]
members = ["crates/tessellator", "crates/svg-generator"]

[dependencies]

[dev-dependencies]
